### ISSUE TITLE
Yes/No dialog is not resizable, Yes/No/Cancel is 

### ISSUE THREAD

**Issue by alanocallaghan** [qupath/qupath-fxtras#26]
This is inconsistent and weird. Also true in main qupath deprecated classes: https://github.com/qupath/qupath/blob/cae379e10c3f6479eeebccc36bf168f891f1df1d/qupath-gui-fx/src/main/java/qupath/lib/gui/dialogs/Dialogs.java#L189

**Comment by petebankhead** [comment]
Fair... should it be resizable or not?

My intuition says 'no', but my intuition also says that there's probably some dialog somewhere that defaults to the wrong size and truncates the text, so 'yes' might be safer... until someone accidentally clicks the title bar and extends the dialog to full screen, which looks stupid.

**Comment by alanocallaghan** [comment]
Yeah I also default to "No", in the hopes that it'll pick the right size based on the text, maybe...? At least default to that until somebody breaks it

**Comment by petebankhead** [comment]
Made non-resizable for use in QuPath v0.5.0
